redress: MultiClassTsetlinMachine.c MultiClassTsetlinMachine.h TsetlinMachine.c TsetlinMachine.h redress.c
	gcc -Wall -O3 -ffast-math -o redress redress.c MultiClassTsetlinMachine.c TsetlinMachine.c 

clean:
	rm *.o redress
